/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BucketUsage
 */
export interface BucketUsage {
    /**
     * 
     * @type {number}
     * @memberof BucketUsage
     */
    usage: number;
    /**
     * 
     * @type {string}
     * @memberof BucketUsage
     */
    bucket?: string;
}

/**
 * Check if a given object implements the BucketUsage interface.
 */
export function instanceOfBucketUsage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "usage" in value;

    return isInstance;
}

export function BucketUsageFromJSON(json: any): BucketUsage {
    return BucketUsageFromJSONTyped(json, false);
}

export function BucketUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usage': json['usage'],
        'bucket': !exists(json, 'bucket') ? undefined : json['bucket'],
    };
}

export function BucketUsageToJSON(value?: BucketUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usage': value.usage,
        'bucket': value.bucket,
    };
}

