/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface IdNameSlugOrmBase
 */
export interface IdNameSlugOrmBase {
    /**
     * 
     * @type {string}
     * @memberof IdNameSlugOrmBase
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IdNameSlugOrmBase
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IdNameSlugOrmBase
     */
    slug: string;
}

/**
 * Check if a given object implements the IdNameSlugOrmBase interface.
 */
export function instanceOfIdNameSlugOrmBase(value: object): value is IdNameSlugOrmBase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function IdNameSlugOrmBaseFromJSON(json: any): IdNameSlugOrmBase {
    return IdNameSlugOrmBaseFromJSONTyped(json, false);
}

export function IdNameSlugOrmBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdNameSlugOrmBase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
    };
}

export function IdNameSlugOrmBaseToJSON(value?: IdNameSlugOrmBase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

