/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface LeverInList
 */
export interface LeverInList {
    /**
     * 
     * @type {string}
     * @memberof LeverInList
     */
    slug: string;
    /**
     * Lever name
     * @type {string}
     * @memberof LeverInList
     */
    name: string;
    /**
     * Lever description
     * @type {string}
     * @memberof LeverInList
     */
    description: string;
    /**
     * Lever display order
     * @type {number}
     * @memberof LeverInList
     */
    order?: number;
    /**
     * Lever default value
     * @type {string}
     * @memberof LeverInList
     */
    defaultValue: string;
}

/**
 * Check if a given object implements the LeverInList interface.
 */
export function instanceOfLeverInList(value: object): value is LeverInList {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('defaultValue' in value) || value['defaultValue'] === undefined) return false;
    return true;
}

export function LeverInListFromJSON(json: any): LeverInList {
    return LeverInListFromJSONTyped(json, false);
}

export function LeverInListFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeverInList {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'defaultValue': json['default_value'],
    };
}

export function LeverInListToJSON(value?: LeverInList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'order': value['order'],
        'default_value': value['defaultValue'],
    };
}

