/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeverInList
 */
export interface LeverInList {
    /**
     * 
     * @type {string}
     * @memberof LeverInList
     */
    slug: string;
    /**
     * Lever name
     * @type {string}
     * @memberof LeverInList
     */
    name: string;
    /**
     * Lever description
     * @type {string}
     * @memberof LeverInList
     */
    description: string;
    /**
     * Lever display order
     * @type {number}
     * @memberof LeverInList
     */
    order?: number;
    /**
     * Lever default value
     * @type {string}
     * @memberof LeverInList
     */
    defaultValue: string;
}

/**
 * Check if a given object implements the LeverInList interface.
 */
export function instanceOfLeverInList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "defaultValue" in value;

    return isInstance;
}

export function LeverInListFromJSON(json: any): LeverInList {
    return LeverInListFromJSONTyped(json, false);
}

export function LeverInListFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeverInList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'defaultValue': json['default_value'],
    };
}

export function LeverInListToJSON(value?: LeverInList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'description': value.description,
        'order': value.order,
        'default_value': value.defaultValue,
    };
}

