/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { TimeUnits } from './TimeUnits.js';
import {
    TimeUnitsFromJSON,
    TimeUnitsFromJSONTyped,
    TimeUnitsToJSON,
} from './TimeUnits.js';

/**
 * 
 * @export
 * @interface PlanInDbBase
 */
export interface PlanInDbBase {
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    alternativeId?: string;
    /**
     * 
     * @type {number}
     * @memberof PlanInDbBase
     */
    displayOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    displayDescription?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PlanInDbBase
     */
    displayExtraAttributes?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PlanInDbBase
     */
    maxSubscribers?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInDbBase
     */
    isSelfServe?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInDbBase
     */
    isPublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInDbBase
     */
    autoRenew?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlanInDbBase
     */
    durationPeriod?: number;
    /**
     * 
     * @type {TimeUnits}
     * @memberof PlanInDbBase
     */
    durationUnit?: TimeUnits;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    id: string;
}



/**
 * Check if a given object implements the PlanInDbBase interface.
 */
export function instanceOfPlanInDbBase(value: object): value is PlanInDbBase {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PlanInDbBaseFromJSON(json: any): PlanInDbBase {
    return PlanInDbBaseFromJSONTyped(json, false);
}

export function PlanInDbBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanInDbBase {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'alternativeId': json['alternative_id'] == null ? undefined : json['alternative_id'],
        'displayOrder': json['display_order'] == null ? undefined : json['display_order'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'displayDescription': json['display_description'] == null ? undefined : json['display_description'],
        'displayExtraAttributes': json['display_extra_attributes'] == null ? undefined : json['display_extra_attributes'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'maxSubscribers': json['max_subscribers'] == null ? undefined : json['max_subscribers'],
        'isSelfServe': json['is_self_serve'] == null ? undefined : json['is_self_serve'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'autoRenew': json['auto_renew'] == null ? undefined : json['auto_renew'],
        'durationPeriod': json['duration_period'] == null ? undefined : json['duration_period'],
        'durationUnit': json['duration_unit'] == null ? undefined : TimeUnitsFromJSON(json['duration_unit']),
        'productId': json['product_id'],
        'id': json['id'],
    };
}

export function PlanInDbBaseToJSON(value?: PlanInDbBase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slug': value['slug'],
        'alternative_id': value['alternativeId'],
        'display_order': value['displayOrder'],
        'display_name': value['displayName'],
        'display_description': value['displayDescription'],
        'display_extra_attributes': value['displayExtraAttributes'],
        'description': value['description'],
        'name': value['name'],
        'max_subscribers': value['maxSubscribers'],
        'is_self_serve': value['isSelfServe'],
        'is_public': value['isPublic'],
        'auto_renew': value['autoRenew'],
        'duration_period': value['durationPeriod'],
        'duration_unit': TimeUnitsToJSON(value['durationUnit']),
        'product_id': value['productId'],
        'id': value['id'],
    };
}

