/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    alternativeId?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    id: string;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "organizationId" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alternativeId': !exists(json, 'alternative_id') ? undefined : json['alternative_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'organizationId': json['organization_id'],
        'slug': json['slug'],
        'id': json['id'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alternative_id': value.alternativeId,
        'description': value.description,
        'name': value.name,
        'organization_id': value.organizationId,
        'slug': value.slug,
        'id': value.id,
    };
}

