/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionInDbBase
 */
export interface SubscriptionInDbBase {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    renewPlanId?: string;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionInDbBase
     */
    renewAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionInDbBase
     */
    lastRenewedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionInDbBase
     */
    maxSubscribers?: number;
}

/**
 * Check if a given object implements the SubscriptionInDbBase interface.
 */
export function instanceOfSubscriptionInDbBase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "planId" in value;
    isInstance = isInstance && "renewAt" in value;
    isInstance = isInstance && "lastRenewedAt" in value;

    return isInstance;
}

export function SubscriptionInDbBaseFromJSON(json: any): SubscriptionInDbBase {
    return SubscriptionInDbBaseFromJSONTyped(json, false);
}

export function SubscriptionInDbBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionInDbBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'planId': json['plan_id'],
        'renewPlanId': !exists(json, 'renew_plan_id') ? undefined : json['renew_plan_id'],
        'renewAt': (new Date(json['renew_at'])),
        'lastRenewedAt': (new Date(json['last_renewed_at'])),
        'maxSubscribers': !exists(json, 'max_subscribers') ? undefined : json['max_subscribers'],
    };
}

export function SubscriptionInDbBaseToJSON(value?: SubscriptionInDbBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'plan_id': value.planId,
        'renew_plan_id': value.renewPlanId,
        'renew_at': (value.renewAt.toISOString()),
        'last_renewed_at': (value.lastRenewedAt.toISOString()),
        'max_subscribers': value.maxSubscribers,
    };
}

