/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SubscriptionCustomerInDbBase
 */
export interface SubscriptionCustomerInDbBase {
    /**
     * 
     * @type {object}
     * @memberof SubscriptionCustomerInDbBase
     */
    metadata?: object;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCustomerInDbBase
     */
    isAdministrator?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCustomerInDbBase
     */
    isSubscriber?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCustomerInDbBase
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCustomerInDbBase
     */
    subscriptionId: string;
}

/**
 * Check if a given object implements the SubscriptionCustomerInDbBase interface.
 */
export function instanceOfSubscriptionCustomerInDbBase(value: object): value is SubscriptionCustomerInDbBase {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    return true;
}

export function SubscriptionCustomerInDbBaseFromJSON(json: any): SubscriptionCustomerInDbBase {
    return SubscriptionCustomerInDbBaseFromJSONTyped(json, false);
}

export function SubscriptionCustomerInDbBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCustomerInDbBase {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata_'] == null ? undefined : json['metadata_'],
        'isAdministrator': json['is_administrator'] == null ? undefined : json['is_administrator'],
        'isSubscriber': json['is_subscriber'] == null ? undefined : json['is_subscriber'],
        'customerId': json['customer_id'],
        'subscriptionId': json['subscription_id'],
    };
}

export function SubscriptionCustomerInDbBaseToJSON(value?: SubscriptionCustomerInDbBase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata_': value['metadata'],
        'is_administrator': value['isAdministrator'],
        'is_subscriber': value['isSubscriber'],
        'customer_id': value['customerId'],
        'subscription_id': value['subscriptionId'],
    };
}

