/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  LeverUsage,
  MeteredUsageIn,
  MeteringRecord,
} from '../models';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LeverUsageFromJSON,
    LeverUsageToJSON,
    MeteredUsageInFromJSON,
    MeteredUsageInToJSON,
    MeteringRecordFromJSON,
    MeteringRecordToJSON,
} from '../models';

export interface GetLeverUsageForCustomerRequest {
    customerId: string;
    productSlug: string;
    leverSlug: string;
}

export interface GetMeteringIdLeversUsageForCustomerRequest {
    customerId: string;
    productSlug: string;
    meteringId: string;
}

export interface ReportMeteredUsageForCustomerRequest {
    customerId: string;
    productSlug: string;
    meteringId: string;
    meteredUsageIn: MeteredUsageIn;
}

/**
 * 
 */
export class MeteredUsageApi extends runtime.BaseAPI {

    /**
     * Get Lever Usage For Customer
     */
    async getLeverUsageForCustomerRaw(requestParameters: GetLeverUsageForCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeverUsage>> {
        if (requestParameters.customerId === null || requestParameters.customerId === undefined) {
            throw new runtime.RequiredError('customerId','Required parameter requestParameters.customerId was null or undefined when calling getLeverUsageForCustomer.');
        }

        if (requestParameters.productSlug === null || requestParameters.productSlug === undefined) {
            throw new runtime.RequiredError('productSlug','Required parameter requestParameters.productSlug was null or undefined when calling getLeverUsageForCustomer.');
        }

        if (requestParameters.leverSlug === null || requestParameters.leverSlug === undefined) {
            throw new runtime.RequiredError('leverSlug','Required parameter requestParameters.leverSlug was null or undefined when calling getLeverUsageForCustomer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2ClientCredentials", []);
        }

        const response = await this.request({
            path: `/api/v1/customers/{customer_id}/products/{product_slug}/levers/{lever_slug}/usage`.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters.customerId))).replace(`{${"product_slug"}}`, encodeURIComponent(String(requestParameters.productSlug))).replace(`{${"lever_slug"}}`, encodeURIComponent(String(requestParameters.leverSlug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeverUsageFromJSON(jsonValue));
    }

    /**
     * Get Lever Usage For Customer
     */
    async getLeverUsageForCustomer(requestParameters: GetLeverUsageForCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeverUsage> {
        const response = await this.getLeverUsageForCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Metering Id Levers Usage For Customer
     */
    async getMeteringIdLeversUsageForCustomerRaw(requestParameters: GetMeteringIdLeversUsageForCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: LeverUsage; }>> {
        if (requestParameters.customerId === null || requestParameters.customerId === undefined) {
            throw new runtime.RequiredError('customerId','Required parameter requestParameters.customerId was null or undefined when calling getMeteringIdLeversUsageForCustomer.');
        }

        if (requestParameters.productSlug === null || requestParameters.productSlug === undefined) {
            throw new runtime.RequiredError('productSlug','Required parameter requestParameters.productSlug was null or undefined when calling getMeteringIdLeversUsageForCustomer.');
        }

        if (requestParameters.meteringId === null || requestParameters.meteringId === undefined) {
            throw new runtime.RequiredError('meteringId','Required parameter requestParameters.meteringId was null or undefined when calling getMeteringIdLeversUsageForCustomer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2ClientCredentials", []);
        }

        const response = await this.request({
            path: `/api/v1/customers/{customer_id}/products/{product_slug}/usage/{metering_id}`.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters.customerId))).replace(`{${"product_slug"}}`, encodeURIComponent(String(requestParameters.productSlug))).replace(`{${"metering_id"}}`, encodeURIComponent(String(requestParameters.meteringId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, LeverUsageFromJSON));
    }

    /**
     * Get Metering Id Levers Usage For Customer
     */
    async getMeteringIdLeversUsageForCustomer(requestParameters: GetMeteringIdLeversUsageForCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: LeverUsage; }> {
        const response = await this.getMeteringIdLeversUsageForCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Report Metered Usage For Customer
     */
    async reportMeteredUsageForCustomerRaw(requestParameters: ReportMeteredUsageForCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeteringRecord>> {
        if (requestParameters.customerId === null || requestParameters.customerId === undefined) {
            throw new runtime.RequiredError('customerId','Required parameter requestParameters.customerId was null or undefined when calling reportMeteredUsageForCustomer.');
        }

        if (requestParameters.productSlug === null || requestParameters.productSlug === undefined) {
            throw new runtime.RequiredError('productSlug','Required parameter requestParameters.productSlug was null or undefined when calling reportMeteredUsageForCustomer.');
        }

        if (requestParameters.meteringId === null || requestParameters.meteringId === undefined) {
            throw new runtime.RequiredError('meteringId','Required parameter requestParameters.meteringId was null or undefined when calling reportMeteredUsageForCustomer.');
        }

        if (requestParameters.meteredUsageIn === null || requestParameters.meteredUsageIn === undefined) {
            throw new runtime.RequiredError('meteredUsageIn','Required parameter requestParameters.meteredUsageIn was null or undefined when calling reportMeteredUsageForCustomer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2ClientCredentials", []);
        }

        const response = await this.request({
            path: `/api/v1/customers/{customer_id}/products/{product_slug}/usage/{metering_id}`.replace(`{${"customer_id"}}`, encodeURIComponent(String(requestParameters.customerId))).replace(`{${"product_slug"}}`, encodeURIComponent(String(requestParameters.productSlug))).replace(`{${"metering_id"}}`, encodeURIComponent(String(requestParameters.meteringId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MeteredUsageInToJSON(requestParameters.meteredUsageIn),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeteringRecordFromJSON(jsonValue));
    }

    /**
     * Report Metered Usage For Customer
     */
    async reportMeteredUsageForCustomer(requestParameters: ReportMeteredUsageForCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeteringRecord> {
        const response = await this.reportMeteredUsageForCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
