/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BucketUsage
 */
export interface BucketUsage {
    /**
     * 
     * @type {number}
     * @memberof BucketUsage
     */
    'usage': number;
    /**
     * 
     * @type {string}
     * @memberof BucketUsage
     */
    'bucket'?: string;
}

