/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerInDbBase
 */
export interface CustomerInDbBase {
    /**
     * 
     * @type {string}
     * @memberof CustomerInDbBase
     */
    'id': string;
    /**
     * 
     * @type {object}
     * @memberof CustomerInDbBase
     */
    'metadata_'?: object;
    /**
     * 
     * @type {string}
     * @memberof CustomerInDbBase
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInDbBase
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInDbBase
     */
    'alternative_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInDbBase
     */
    'organization_id': string;
}

