/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Lever
 */
export interface Lever {
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof Lever
     */
    'display_order'?: number;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'display_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'display_description'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Lever
     */
    'display_extra_attributes'?: { [key: string]: string; };
    /**
     * 
     * @type {object}
     * @memberof Lever
     */
    'configuration'?: object;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'entitlement_display_value_template'?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'entitlement_display_name_template'?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'entitlement_display_description_template'?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'lever_type_id': string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    'product_id': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Lever
     */
    'metering_ids': Array<string>;
    /**
     * 
     * @type {object}
     * @memberof Lever
     */
    'entitlement_schema_json'?: object;
}

