/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LeverInList
 */
export interface LeverInList {
    /**
     * 
     * @type {string}
     * @memberof LeverInList
     */
    'slug': string;
    /**
     * Lever name
     * @type {string}
     * @memberof LeverInList
     */
    'name': string;
    /**
     * Lever description
     * @type {string}
     * @memberof LeverInList
     */
    'description': string;
    /**
     * Lever display order
     * @type {number}
     * @memberof LeverInList
     */
    'order'?: number;
    /**
     * Lever default value
     * @type {string}
     * @memberof LeverInList
     */
    'default_value': string;
}

