/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrganizationCustomerCreate
 */
export interface OrganizationCustomerCreate {
    /**
     * 
     * @type {object}
     * @memberof OrganizationCustomerCreate
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCustomerCreate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCustomerCreate
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCustomerCreate
     */
    'alternative_id'?: string;
}

