/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlanEntitlement
 */
export interface PlanEntitlement {
    /**
     * Formatted text representation of the entitlement value
     * @type {string}
     * @memberof PlanEntitlement
     */
    'formatted_value': string;
    /**
     * Actual entitlement value
     * @type {any}
     * @memberof PlanEntitlement
     */
    'value'?: any;
    /**
     * Entitlement name
     * @type {string}
     * @memberof PlanEntitlement
     */
    'name': string;
    /**
     * Entitlement name
     * @type {string}
     * @memberof PlanEntitlement
     */
    'lever_name': string;
    /**
     * Entitlement description
     * @type {string}
     * @memberof PlanEntitlement
     */
    'description': string;
    /**
     * Entitlement display order
     * @type {number}
     * @memberof PlanEntitlement
     */
    'order'?: number;
    /**
     * Entitlement configuration object
     * @type {object}
     * @memberof PlanEntitlement
     */
    'configuration'?: object;
}

