/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlanInList
 */
export interface PlanInList {
    /**
     * 
     * @type {string}
     * @memberof PlanInList
     */
    'slug': string;
    /**
     * Plan name
     * @type {string}
     * @memberof PlanInList
     */
    'name': string;
    /**
     * Plan description
     * @type {string}
     * @memberof PlanInList
     */
    'description': string;
    /**
     * Plan display order
     * @type {number}
     * @memberof PlanInList
     */
    'order'?: number;
}

