/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TimeUnits } from './time-units';

/**
 * 
 * @export
 * @interface PlanInDbBase
 */
export interface PlanInDbBase {
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'alternative_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof PlanInDbBase
     */
    'display_order'?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'display_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'display_description'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PlanInDbBase
     */
    'display_extra_attributes'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PlanInDbBase
     */
    'max_subscribers'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInDbBase
     */
    'is_self_serve'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInDbBase
     */
    'is_public'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInDbBase
     */
    'auto_renew'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlanInDbBase
     */
    'duration_period'?: number;
    /**
     * 
     * @type {TimeUnits}
     * @memberof PlanInDbBase
     */
    'duration_unit'?: TimeUnits;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'product_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlanInDbBase
     */
    'id': string;
}

