/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlanSubscriptionCreate
 */
export interface PlanSubscriptionCreate {
    /**
     * 
     * @type {object}
     * @memberof PlanSubscriptionCreate
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof PlanSubscriptionCreate
     */
    'customer_id': string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanSubscriptionCreate
     */
    'is_subscriber'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlanSubscriptionCreate
     */
    'max_subscribers'?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanSubscriptionCreate
     */
    'renew_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanSubscriptionCreate
     */
    'auto_renew'?: boolean;
}

