/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionInDbBase
 */
export interface SubscriptionInDbBase {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    'plan_id': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    'renew_plan_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    'renew_at': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionInDbBase
     */
    'last_renewed_at': string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionInDbBase
     */
    'max_subscribers'?: number;
}

