/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionUpdateWithSlugs
 */
export interface SubscriptionUpdateWithSlugs {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'plan_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'renew_plan_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'plan_slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'renew_plan_slug'?: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'max_subscribers'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'auto_renew'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUpdateWithSlugs
     */
    'renew_at'?: string;
}

