/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionCustomerCreate
 */
export interface SubscriptionCustomerCreate {
    /**
     * 
     * @type {object}
     * @memberof SubscriptionCustomerCreate
     */
    'metadata'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCustomerCreate
     */
    'is_administrator'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCustomerCreate
     */
    'is_subscriber'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCustomerCreate
     */
    'customer_id': string;
}

