/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionCreate
 */
export interface SubscriptionCreate {
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCreate
     */
    'auto_renew': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionCreate
     */
    'is_active': boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    'plan_id': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    'renew_plan_id': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    'renew_at': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    'last_renewed_at': string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionCreate
     */
    'max_subscribers'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    'start_at': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    'alternative_id'?: string;
}

