/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerId
 */
export interface CustomerId {
}

/**
 * Check if a given object implements the CustomerId interface.
 */
export function instanceOfCustomerId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomerIdFromJSON(json: any): CustomerId {
    return CustomerIdFromJSONTyped(json, false);
}

export function CustomerIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerId {
    return json;
}

export function CustomerIdToJSON(value?: CustomerId | null): any {
    return value;
}

