/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BucketUsage } from './BucketUsage';
import {
    BucketUsageFromJSON,
    BucketUsageFromJSONTyped,
    BucketUsageToJSON,
} from './BucketUsage';

/**
 * 
 * @export
 * @interface LeverUsage
 */
export interface LeverUsage {
    /**
     * 
     * @type {number}
     * @memberof LeverUsage
     */
    total: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof LeverUsage
     */
    byBucket: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: Array<BucketUsage>; }}
     * @memberof LeverUsage
     */
    bySubscription: { [key: string]: Array<BucketUsage>; };
}

/**
 * Check if a given object implements the LeverUsage interface.
 */
export function instanceOfLeverUsage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "byBucket" in value;
    isInstance = isInstance && "bySubscription" in value;

    return isInstance;
}

export function LeverUsageFromJSON(json: any): LeverUsage {
    return LeverUsageFromJSONTyped(json, false);
}

export function LeverUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeverUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'byBucket': json['by_bucket'],
        'bySubscription': json['by_subscription'],
    };
}

export function LeverUsageToJSON(value?: LeverUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'by_bucket': value.byBucket,
        'by_subscription': value.bySubscription,
    };
}

