/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Lever
 */
export interface Lever {
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Lever
     */
    displayOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    displayDescription?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Lever
     */
    displayExtraAttributes?: { [key: string]: string; };
    /**
     * 
     * @type {object}
     * @memberof Lever
     */
    configuration?: object;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    entitlementDisplayValueTemplate?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    entitlementDisplayNameTemplate?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    entitlementDisplayDescriptionTemplate?: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    leverTypeId: string;
    /**
     * 
     * @type {string}
     * @memberof Lever
     */
    productId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Lever
     */
    meteringIds: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof Lever
     */
    entitlementSchemaJson?: object;
}

/**
 * Check if a given object implements the Lever interface.
 */
export function instanceOfLever(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "leverTypeId" in value;
    isInstance = isInstance && "productId" in value;
    isInstance = isInstance && "meteringIds" in value;

    return isInstance;
}

export function LeverFromJSON(json: any): Lever {
    return LeverFromJSONTyped(json, false);
}

export function LeverFromJSONTyped(json: any, ignoreDiscriminator: boolean): Lever {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'id': json['id'],
        'displayOrder': !exists(json, 'display_order') ? undefined : json['display_order'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'displayDescription': !exists(json, 'display_description') ? undefined : json['display_description'],
        'displayExtraAttributes': !exists(json, 'display_extra_attributes') ? undefined : json['display_extra_attributes'],
        'configuration': !exists(json, 'configuration') ? undefined : json['configuration'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'entitlementDisplayValueTemplate': !exists(json, 'entitlement_display_value_template') ? undefined : json['entitlement_display_value_template'],
        'entitlementDisplayNameTemplate': !exists(json, 'entitlement_display_name_template') ? undefined : json['entitlement_display_name_template'],
        'entitlementDisplayDescriptionTemplate': !exists(json, 'entitlement_display_description_template') ? undefined : json['entitlement_display_description_template'],
        'leverTypeId': json['lever_type_id'],
        'productId': json['product_id'],
        'meteringIds': json['metering_ids'],
        'entitlementSchemaJson': !exists(json, 'entitlement_schema_json') ? undefined : json['entitlement_schema_json'],
    };
}

export function LeverToJSON(value?: Lever | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'id': value.id,
        'display_order': value.displayOrder,
        'display_name': value.displayName,
        'display_description': value.displayDescription,
        'display_extra_attributes': value.displayExtraAttributes,
        'configuration': value.configuration,
        'description': value.description,
        'name': value.name,
        'entitlement_display_value_template': value.entitlementDisplayValueTemplate,
        'entitlement_display_name_template': value.entitlementDisplayNameTemplate,
        'entitlement_display_description_template': value.entitlementDisplayDescriptionTemplate,
        'lever_type_id': value.leverTypeId,
        'product_id': value.productId,
        'metering_ids': value.meteringIds,
        'entitlement_schema_json': value.entitlementSchemaJson,
    };
}

