/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MeteredUsageIn
 */
export interface MeteredUsageIn {
    /**
     * 
     * @type {number}
     * @memberof MeteredUsageIn
     */
    usage: number;
    /**
     * 
     * @type {string}
     * @memberof MeteredUsageIn
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteredUsageIn
     */
    bucket?: string;
}

/**
 * Check if a given object implements the MeteredUsageIn interface.
 */
export function instanceOfMeteredUsageIn(value: object): value is MeteredUsageIn {
    if (!('usage' in value) || value['usage'] === undefined) return false;
    return true;
}

export function MeteredUsageInFromJSON(json: any): MeteredUsageIn {
    return MeteredUsageInFromJSONTyped(json, false);
}

export function MeteredUsageInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteredUsageIn {
    if (json == null) {
        return json;
    }
    return {
        
        'usage': json['usage'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
    };
}

export function MeteredUsageInToJSON(value?: MeteredUsageIn | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'usage': value['usage'],
        'subscription_id': value['subscriptionId'],
        'bucket': value['bucket'],
    };
}

