/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MeteringRecord
 */
export interface MeteringRecord {
    /**
     * 
     * @type {string}
     * @memberof MeteringRecord
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof MeteringRecord
     */
    isAllocated?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MeteringRecord
     */
    usage: number;
    /**
     * 
     * @type {string}
     * @memberof MeteringRecord
     */
    meteringId: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringRecord
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringRecord
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringRecord
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringRecord
     */
    bucket?: string;
}

/**
 * Check if a given object implements the MeteringRecord interface.
 */
export function instanceOfMeteringRecord(value: object): value is MeteringRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('meteringId' in value) || value['meteringId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function MeteringRecordFromJSON(json: any): MeteringRecord {
    return MeteringRecordFromJSONTyped(json, false);
}

export function MeteringRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteringRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'isAllocated': json['is_allocated'] == null ? undefined : json['is_allocated'],
        'usage': json['usage'],
        'meteringId': json['metering_id'],
        'customerId': json['customer_id'],
        'productId': json['product_id'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
    };
}

export function MeteringRecordToJSON(value?: MeteringRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'is_allocated': value['isAllocated'],
        'usage': value['usage'],
        'metering_id': value['meteringId'],
        'customer_id': value['customerId'],
        'product_id': value['productId'],
        'subscription_id': value['subscriptionId'],
        'bucket': value['bucket'],
    };
}

