/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeteredUsageIn
 */
export interface MeteredUsageIn {
    /**
     * 
     * @type {number}
     * @memberof MeteredUsageIn
     */
    usage: number;
    /**
     * 
     * @type {string}
     * @memberof MeteredUsageIn
     */
    subscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteredUsageIn
     */
    bucket?: string;
}

/**
 * Check if a given object implements the MeteredUsageIn interface.
 */
export function instanceOfMeteredUsageIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "usage" in value;

    return isInstance;
}

export function MeteredUsageInFromJSON(json: any): MeteredUsageIn {
    return MeteredUsageInFromJSONTyped(json, false);
}

export function MeteredUsageInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteredUsageIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usage': json['usage'],
        'subscriptionId': !exists(json, 'subscription_id') ? undefined : json['subscription_id'],
        'bucket': !exists(json, 'bucket') ? undefined : json['bucket'],
    };
}

export function MeteredUsageInToJSON(value?: MeteredUsageIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usage': value.usage,
        'subscription_id': value.subscriptionId,
        'bucket': value.bucket,
    };
}

