/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationCustomerCreate
 */
export interface OrganizationCustomerCreate {
    /**
     * 
     * @type {object}
     * @memberof OrganizationCustomerCreate
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCustomerCreate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCustomerCreate
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCustomerCreate
     */
    alternativeId?: string;
}

/**
 * Check if a given object implements the OrganizationCustomerCreate interface.
 */
export function instanceOfOrganizationCustomerCreate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationCustomerCreateFromJSON(json: any): OrganizationCustomerCreate {
    return OrganizationCustomerCreateFromJSONTyped(json, false);
}

export function OrganizationCustomerCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationCustomerCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'alternativeId': !exists(json, 'alternative_id') ? undefined : json['alternative_id'],
    };
}

export function OrganizationCustomerCreateToJSON(value?: OrganizationCustomerCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': value.metadata,
        'name': value.name,
        'email': value.email,
        'alternative_id': value.alternativeId,
    };
}

