/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PlanEntitlement
 */
export interface PlanEntitlement {
    /**
     * Formatted text representation of the entitlement value
     * @type {string}
     * @memberof PlanEntitlement
     */
    formattedValue: string;
    /**
     * Actual entitlement value
     * @type {any}
     * @memberof PlanEntitlement
     */
    value?: any | null;
    /**
     * Entitlement name
     * @type {string}
     * @memberof PlanEntitlement
     */
    name: string;
    /**
     * Entitlement name
     * @type {string}
     * @memberof PlanEntitlement
     */
    leverName: string;
    /**
     * Entitlement description
     * @type {string}
     * @memberof PlanEntitlement
     */
    description: string;
    /**
     * Entitlement display order
     * @type {number}
     * @memberof PlanEntitlement
     */
    order?: number;
    /**
     * Entitlement configuration object
     * @type {object}
     * @memberof PlanEntitlement
     */
    configuration?: object;
}

/**
 * Check if a given object implements the PlanEntitlement interface.
 */
export function instanceOfPlanEntitlement(value: object): value is PlanEntitlement {
    if (!('formattedValue' in value) || value['formattedValue'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('leverName' in value) || value['leverName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PlanEntitlementFromJSON(json: any): PlanEntitlement {
    return PlanEntitlementFromJSONTyped(json, false);
}

export function PlanEntitlementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanEntitlement {
    if (json == null) {
        return json;
    }
    return {
        
        'formattedValue': json['formatted_value'],
        'value': json['value'] == null ? undefined : json['value'],
        'name': json['name'],
        'leverName': json['lever_name'],
        'description': json['description'],
        'order': json['order'] == null ? undefined : json['order'],
        'configuration': json['configuration'] == null ? undefined : json['configuration'],
    };
}

export function PlanEntitlementToJSON(value?: PlanEntitlement | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'formatted_value': value['formattedValue'],
        'value': value['value'],
        'name': value['name'],
        'lever_name': value['leverName'],
        'description': value['description'],
        'order': value['order'],
        'configuration': value['configuration'],
    };
}

