/* tslint:disable */
/* eslint-disable */
/**
 * Planship API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PlanSubscriptionCreate
 */
export interface PlanSubscriptionCreate {
    /**
     * 
     * @type {object}
     * @memberof PlanSubscriptionCreate
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof PlanSubscriptionCreate
     */
    customerId: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanSubscriptionCreate
     */
    isSubscriber?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlanSubscriptionCreate
     */
    maxSubscribers?: number;
    /**
     * 
     * @type {Date}
     * @memberof PlanSubscriptionCreate
     */
    renewAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PlanSubscriptionCreate
     */
    autoRenew?: boolean;
}

/**
 * Check if a given object implements the PlanSubscriptionCreate interface.
 */
export function instanceOfPlanSubscriptionCreate(value: object): value is PlanSubscriptionCreate {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function PlanSubscriptionCreateFromJSON(json: any): PlanSubscriptionCreate {
    return PlanSubscriptionCreateFromJSONTyped(json, false);
}

export function PlanSubscriptionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanSubscriptionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'customerId': json['customer_id'],
        'isSubscriber': json['is_subscriber'] == null ? undefined : json['is_subscriber'],
        'maxSubscribers': json['max_subscribers'] == null ? undefined : json['max_subscribers'],
        'renewAt': json['renew_at'] == null ? undefined : (new Date(json['renew_at'])),
        'autoRenew': json['auto_renew'] == null ? undefined : json['auto_renew'],
    };
}

export function PlanSubscriptionCreateToJSON(value?: PlanSubscriptionCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': value['metadata'],
        'customer_id': value['customerId'],
        'is_subscriber': value['isSubscriber'],
        'max_subscribers': value['maxSubscribers'],
        'renew_at': value['renewAt'] == null ? undefined : ((value['renewAt']).toISOString()),
        'auto_renew': value['autoRenew'],
    };
}

